name: mnr-crm ci/cd

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: caching
        id: caching
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - if: ${{ steps.caching.outputs.cache-hit != 'true' }}
        name: install
        run: npm ci --legacy-peer-deps

  test:
    runs-on: ubuntu-latest
    needs:   install
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - name: restore cache
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: test
        run: npm run test:ci

  client:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: restore cache
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: build
        run: npm run build:client
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: antantaru/mnr-client:latest
          platforms: linux/amd64
          file: ci-client.Dockerfile
      - name: deploy by ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            docker stop client-container
            docker rmi antantaru/mnr-client:latest
            docker pull antantaru/mnr-client
            docker run -d -p4200:4200 --name client-container --rm antantaru/mnr-client
          username: root
          host: ${{ secrets.SSH_HOST }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}

  backend:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: restore cache
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: build
        run: npm run build:backend && npm prune --production --legacy-peer-deps
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: antantaru/mnr-backend:latest
          platforms: linux/amd64
          file: ci-backend.Dockerfile
      - name: deploy by ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            docker stop backend-container
            docker rmi antantaru/mnr-backend:latest
            docker pull antantaru/mnr-backend
            docker run -d --env-file="docker_vars.env" --network="host" --name backend-container --rm antantaru/mnr-backend
          username: root
          host: ${{ secrets.SSH_HOST }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}

  docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: restore cache
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: build
        run: npm run build:docs
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: antantaru/mnr-docs
          platforms: linux/amd64
          file: ci-docs.Dockerfile
      - name: deploy by ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            docker stop docs-container
            docker rmi antantaru/mnr-docs:latest
            docker pull antantaru/mnr-docs
            docker run -d -p3000:3000 --name docs-container --rm antantaru/mnr-docs
          username: root
          host: ${{ secrets.SSH_HOST }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}



#      - name: get affected
#        run: npm run test:ci
#      - name: caching
#        id: cache-node-modules
#        uses: actions/cache@v3
#        with:
#          path: node_modules
#          key: node-modules-${{ hashFiles('package-lock.json') }}

#  affected:
#
#    runs-on: ubuntu-latest
#    needs: install
#
#    steps:
#      - name: checkout
#        uses: actions/checkout@v3
#      - name: restore cache
#        id: cache-node-modules
#        uses: actions/cache@v3
#        with:
#          path: node_modules
#          key: node-modules-${{ hashFiles('package-lock.json') }}
#      - name: get affected
#        run: npm run nx print-affected --type=app --select=projects




